apiVersion: v1
kind: ConfigMap
metadata:
  name: todo-config
  namespace: {{ .Values.namespace }}
data:
  NEXT_PUBLIC_API_URL: {{ .Values.config.apiUrl | quote }}
  BETTER_AUTH_URL: {{ .Values.config.authUrl | quote }}
